END_GOBLIN_ALT_TEXTURE = false
END_GOBLIN_CAN_SPAWN_IN_END = true
END_GOBLIN_CAN_SPAWN_IN_OVERWORLD = false
END_GOBLIN_CAN_SPAWN_IN_HELL = false
END_GOBLIN_SPAWN_RATE = 35
END_GOBLIN_SPAWN_RATE_D = 1
END_GOBLIN_GROUP_SIZE = 2
