install_build_tools: &install_build_tools
  run:
    name: install build tools
    command: |
      apk add git

build_carpet: &build_carpet
  run:
    name: build image
    command: |
      cd minecraft-alpine
      ./build.sh 1.14.4

jobs:
  1.14.4:
    docker:
      - image: docker:20.10.12-alpine3.15
    working_directory: ~/repo
    steps:
      - <<: *install_build_tools
      - checkout
      - <<: *build_carpet

workflows:
  build_and_test:
    stages:
      - 1.14.4
