install_build_tools: &install_build_tools
  run:
    name: install build tools
    command: |
      apk add git

default_steps: &default_steps
  steps:
    - <<: *install_build_tools
    - checkout

jobs:
  1.14.4:
    docker:
      - image: docker:20.10.12-alpine3.15
    working_directory: ~/repo
    <<: *default_steps

workflows:
  build_and_test:
    stages:
      - 1.14.4
